# Generated by Django 5.0.6 on 2024-07-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('P', 'ح'), ('S', 'م'), ('C', 'ع'), ('A', 'د'), ('M', 'غ'), ('O', 'ر')], max_length=200, verbose_name='Status'),
        ),
    ]
