# Generated by Django 5.0.6 on 2024-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='birthPlace',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='idealEmployee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='policeDayHonoring',
        ),
        migrations.AddField(
            model_name='customuser',
            name='addressDivision',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Division'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='addressGovernorate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Governorate'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthDivision',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Birth Division'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='birthGovernorate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Birth Governorate'),
        ),
    ]
