# Generated by Django 5.0.6 on 2024-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondName',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Second Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='thirdName',
            field=models.DateField(blank=True, max_length=200, null=True, verbose_name='Third Name'),
        ),
    ]
