# Generated by Django 5.0.6 on 2024-06-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_customuser_secondname_customuser_thirdname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='academicQualifications',
            field=models.TextField(blank=True, null=True, verbose_name='Academic Qualifications'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='academicQualificationsInService',
            field=models.TextField(blank=True, null=True, verbose_name='Academic Qualifications In Service'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='casualVacations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Casual Vacations'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currentEmployer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Employer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='currentRank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Rank'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='decisionNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Decision Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='employmentDate',
            field=models.DateField(blank=True, null=True, verbose_name='Employment Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='graduationYear',
            field=models.DateField(blank=True, null=True, verbose_name='Graduation Year'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='healthInsuranceNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Health Insurance Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insuranceNumber',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurance Number'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='insuranceUmbrella',
            field=models.TextField(blank=True, null=True, verbose_name='Insurance Umbrella'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jobFamily',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Family'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jobStartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Job Start Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='militaryStatus',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Military Status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nationalId',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='National ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='periodicVacations',
            field=models.IntegerField(blank=True, null=True, verbose_name='Periodic Vacations'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='policeDayHonoring',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Police Day Honoring'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='previousEmployer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Previous Employer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='previousHaj',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Previous Haj'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='religion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Religion'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='retirementDate',
            field=models.DateField(blank=True, null=True, verbose_name='Retirement Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='solidarityFund',
            field=models.TextField(blank=True, null=True, verbose_name='Solidarity Fund'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stakeholderFund',
            field=models.TextField(blank=True, null=True, verbose_name='stakeholder Fund'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='topEmployee',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Top Employee'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='secondName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='thirdName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Third Name'),
        ),
    ]
