# Generated by Django 5.0.6 on 2024-07-28 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_customuser_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'Governorate', 'verbose_name_plural': 'Governorates'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='academicQualifications',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Academic Qualifications'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='casualVacations',
            field=models.IntegerField(blank=True, default=6, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casual Vacations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='periodicVacations',
            field=models.IntegerField(blank=True, default=15, editable=False, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Periodic Vacations'),
        ),
    ]
