# Generated by Django 5.0.6 on 2024-07-28 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_division_options_alter_governorate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='casualVacations',
            field=models.IntegerField(blank=True, default=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casual Vacations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='periodicVacations',
            field=models.IntegerField(blank=True, default=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Periodic Vacations'),
        ),
    ]
