# Generated by Django 5.0.6 on 2024-07-28 11:25

import base.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_customuser_casualvacations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ideal Employee',
                'verbose_name_plural': 'Ideal Employees',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.CreateModel(
            name='PoliceDayHonoredEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Police Day Honored Employee',
                'verbose_name_plural': 'Police Day Honored Employee',
                'ordering': ['-updated', '-created'],
            },
        ),
        migrations.DeleteModel(
            name='IdealEmployeeCandidate',
        ),
    ]
