# Generated by Django 5.0.6 on 2024-06-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='penalty',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
