# Generated by Django 5.0.6 on 2024-07-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_idealemployee_policedayhonoredemployee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currentEmploymentStartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Current Employment Start Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='previousEmploymentEndDate',
            field=models.DateField(blank=True, null=True, verbose_name='Previous Employment End Date'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='previousEmploymentStartDate',
            field=models.DateField(blank=True, null=True, verbose_name='Previous Employment Start Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='insuranceUmbrellaDate',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='previousHajDate',
            field=models.DateField(blank=True, null=True, verbose_name='Previous Haj Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solidarityFundDate',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stakeholderFundDate',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
    ]
