# Generated by Django 5.0.6 on 2024-07-28 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_customuser_currentemploymentstartdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeVacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Annual', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى')], max_length=200, verbose_name='Type')),
                ('fromDate', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('toDate', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('days', models.IntegerField(blank=True, null=True, verbose_name='Days')),
                ('remainingBalance', models.IntegerField(blank=True, null=True, verbose_name='Remaining Balance')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee Vacation',
                'verbose_name_plural': 'Employee Vacations',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
