# Generated by Django 5.0.6 on 2024-06-13 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_penalty_description_alter_penalty_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Penalty', 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AlterModelOptions(
            name='secretreport',
            options={'ordering': ['-updated', '-created'], 'verbose_name': 'Secret Report', 'verbose_name_plural': 'Secret Reports'},
        ),
    ]
