# Generated by Django 5.0.6 on 2024-07-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_employeevacation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='remainingBalance',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Remaining Balance'),
        ),
    ]
