# Generated by Django 5.0.6 on 2024-06-25 10:48

import base.models
import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_course_user_alter_penalty_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthDate',
            field=models.DateField(default=datetime.datetime.now, validators=[base.models.validate_date], verbose_name='Birth Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationalId',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_data', message='Enter a valid national id', regex='^([1-9]{1})([0-9]{2})([0-9]{2})([0-9]{2})([0-9]{2})[0-9]{3}([0-9]{1})[0-9]{1}$')], verbose_name='National ID'),
            preserve_default=False,
        ),
    ]
