# Generated by Django 5.0.6 on 2024-07-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_employeevacation_remainingbalance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='days',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Days'),
        ),
    ]
