# Generated by Django 5.0.6 on 2024-07-28 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_employeevacation_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى')], max_length=200, verbose_name='Type'),
        ),
    ]
