# Generated by Django 5.0.6 on 2024-06-25 11:43

import base.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_customuser_birthdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificateObtained',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Obtained Certificate'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='course',
            name='endDate',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='startDate',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='casualVacations',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casual Vacations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='employmentDate',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Employment Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='graduationYear',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='jobStartDate',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Job Start Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nationalId',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_data', message='Enter a valid national id', regex='^([2-3]{1})([0-9]{2})(0[1-9]|1[012])(0[1-9]|[1-2][0-9]|3[0-1])(0[1-4]|[1-2][1-9]|3[1-5]|88)[0-9]{3}([0-9]{1})[0-9]{1}$')], verbose_name='National ID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='periodicVacations',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Periodic Vacations'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='policeDayHonoring',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Police Day Honoring'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='previousHaj',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Previous Haj'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='retirementDate',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Retirement Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='topEmployee',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Ideal Employee'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='penalty',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretreport',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretreport',
            name='name',
            field=models.CharField(default='1', max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='secretreport',
            name='reportDate',
            field=models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Report Date'),
        ),
        migrations.CreateModel(
            name='IdealEmployeeCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topEmployee', models.BooleanField(blank=True, default=False, null=True, verbose_name='Ideal Employee')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Ideal Employee Candidate',
                'verbose_name_plural': 'Ideal Employee Candidates',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
