# Generated by Django 5.0.6 on 2024-07-30 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_employeevacation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Course Address'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
