# Generated by Django 5.0.6 on 2024-06-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_course_certificateobtained_course_grade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='topEmployee',
            new_name='idealEmployee',
        ),
        migrations.RenameField(
            model_name='idealemployeecandidate',
            old_name='topEmployee',
            new_name='idealEmployee',
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='idealemployeecandidate',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='idealemployeecandidate',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='secretreport',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='secretreport',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
