# Generated by Django 5.0.6 on 2024-07-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_course_address_alter_penalty_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
