# Generated by Django 5.0.6 on 2024-07-04 11:26

import base.models
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_topemployee_customuser_idealemployee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'ح'), ('S', 'م'), ('C', 'ع'), ('A', 'د'), ('M', 'غ')], max_length=200, verbose_name='Status')),
                ('dayDate', models.DateField(default=datetime.datetime.now, validators=[base.models.validate_date], verbose_name='Day Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Employee Attendance',
                'verbose_name_plural': 'Employees Attendance',
                'ordering': ['-updated', '-created'],
            },
        ),
    ]
