# Generated by Django 5.0.6 on 2024-08-08 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_division_name_alter_governorate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='casualVacations',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casual Vacations'),
        ),
    ]
