# Generated by Django 5.0.6 on 2024-08-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_division_name_alter_governorate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Qualification Name'),
        ),
    ]
