# Generated by Django 5.0.6 on 2024-08-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_customuser_full_name_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
    ]
