# Generated by Django 5.0.6 on 2024-08-27 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_employeevacation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], default='Male', max_length=200, verbose_name='Gender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('P65%', '65%بالعمل'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
    ]
