# Generated by Django 5.0.6 on 2024-09-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_customuser_gender_alter_employeevacation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Course Name',
                'verbose_name_plural': 'Course Names',
            },
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nickname',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], default='Male', max_length=200, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='insuranceUmbrella',
            field=models.BooleanField(default=False, verbose_name='Insurance Umbrella'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='previousHaj',
            field=models.BooleanField(default=False, verbose_name='Previous Haj'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='religion',
            field=models.CharField(choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحى')], default='Muslim', max_length=200, verbose_name='Religion'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='solidarityFund',
            field=models.BooleanField(default=False, verbose_name='Solidarity Fund'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='stakeholderFund',
            field=models.BooleanField(default=False, verbose_name='stakeholder Fund'),
        ),
    ]
