# Generated by Django 5.0.6 on 2024-09-25 11:34

import base.models
import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_coursename_remove_customuser_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=200, null=True, verbose_name='First Name')),
                ('secondName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Second Name')),
                ('thirdName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Third Name')),
                ('lastName', models.CharField(blank=True, max_length=200, null=True, verbose_name='Last Name')),
                ('birthGovernorate', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birth Governorate')),
                ('birthDivision', models.CharField(blank=True, max_length=200, null=True, verbose_name='Birth Division')),
                ('birthDate', models.DateField(default=datetime.datetime.now, validators=[base.models.validate_date], verbose_name='Birth Date')),
                ('nationalId', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_data', message='Enter a valid national id', regex='^([2-3]{1})([0-9]{2})(0[1-9]|1[012])(0[1-9]|[1-2][0-9]|3[0-1])(0[1-4]|[1-2][1-9]|3[1-5]|88)[0-9]{3}([0-9]{1})[0-9]{1}$')], verbose_name='National ID')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], default='Male', max_length=200, verbose_name='Gender')),
                ('insuranceNumber', models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurance Number')),
                ('healthInsuranceNumber', models.CharField(blank=True, max_length=200, null=True, verbose_name='Health Insurance Number')),
                ('academicQualifications', models.CharField(blank=True, max_length=200, null=True, verbose_name='Academic Qualifications')),
                ('jobFamily', models.CharField(blank=True, max_length=200, null=True, verbose_name='Job Family')),
                ('graduationYear', models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Graduation Year')),
                ('employmentDate', models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Employment Date')),
                ('decisionNumber', models.CharField(blank=True, max_length=200, null=True, verbose_name='Decision Number')),
                ('militaryStatus', models.CharField(blank=True, choices=[('Completed', 'تم الخدمة'), ('Permanently Exempted', 'معافى نهائيًا'), ('Temporarily Exempted', 'معافى مؤقتًا'), ('Draft Evader', 'متخلف عن التجنيد'), ('Deferred Conscription', 'مؤجل التجنيد'), ('Not Required for Conscription', 'غير مطلوب للتجنيد')], max_length=200, null=True, verbose_name='Military Status')),
                ('jobStartDate', models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Job Start Date')),
                ('currentRank', models.CharField(blank=True, choices=[('First Grade A', 'الدرجة الأولى ا'), ('First Grade A', 'الدرجة الأولى ب'), ('Second Grade A', 'الدرجة الثانية ا'), ('Second Grade A', 'الدرجة الثانية ب'), ('Third Grade A', 'الدرجة الثالثة ا'), ('Third Grade A', 'الدرجة الثالثة ب'), ('Fourth Grade A', 'الدرجة الرابعة ا'), ('Fourth Grade A', 'الدرجة الرابعة ب')], max_length=200, null=True, verbose_name='Current Rank')),
                ('previousEmployer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Previous Employer')),
                ('previousEmploymentStartDate', models.DateField(blank=True, null=True, verbose_name='Previous Employment Start Date')),
                ('previousEmploymentEndDate', models.DateField(blank=True, null=True, verbose_name='Previous Employment End Date')),
                ('currentEmployer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Current Employer')),
                ('currentEmploymentStartDate', models.DateField(blank=True, null=True, verbose_name='Current Employment Start Date')),
                ('periodicVacations', models.IntegerField(blank=True, default=21, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Periodic Vacations')),
                ('casualVacations', models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Casual Vacations')),
                ('retirementDate', models.DateField(blank=True, null=True, validators=[base.models.validate_date], verbose_name='Retirement Date')),
                ('solidarityFund', models.BooleanField(default=False, verbose_name='Solidarity Fund')),
                ('solidarityFundDate', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('stakeholderFund', models.BooleanField(default=False, verbose_name='stakeholder Fund')),
                ('stakeholderFundDate', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('insuranceUmbrella', models.BooleanField(default=False, verbose_name='Insurance Umbrella')),
                ('insuranceUmbrellaDate', models.DateField(blank=True, null=True, verbose_name='Joining Date')),
                ('addressGovernorate', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Governorate')),
                ('addressDivision', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address Division')),
                ('religion', models.CharField(choices=[('Muslim', 'مسلم'), ('Christian', 'مسيحى')], default='Muslim', max_length=200, verbose_name='Religion')),
                ('previousHaj', models.BooleanField(default=False, verbose_name='Previous Haj')),
                ('previousHajDate', models.DateField(blank=True, null=True, verbose_name='Previous Haj Date')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeeattendance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='employeevacation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='idealemployee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='user',
        ),
        migrations.RemoveField(
            model_name='policedayhonoredemployee',
            name='user',
        ),
        migrations.RemoveField(
            model_name='secretreport',
            name='user',
        ),
        migrations.AddField(
            model_name='course',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='employeevacation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='idealemployee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='penalty',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to='base.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='policedayhonoredemployee',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Employee'),
        ),
        migrations.AddField(
            model_name='secretreport',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.employee', verbose_name='Employee'),
        ),
    ]
