# Generated by Django 5.0.6 on 2024-12-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_employee_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governorate',
            name='national_governorate_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='National Governorate ID'),
            preserve_default=False,
        ),
    ]
