# Generated by Django 5.0.6 on 2024-12-17 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_governorate_national_governorate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='birthGovernorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.governorate', verbose_name='Birth Governorate'),
        ),
    ]
