# Generated by Django 5.0.6 on 2025-01-09 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_employee_birthgovernorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='dayDate',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Day Date'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'dayDate')},
        ),
    ]
