# Generated by Django 5.0.6 on 2025-01-13 07:55

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_image',
            field=models.ImageField(blank=True, null=True, upload_to=base.models.Employee.employee_image_path, verbose_name='Employee Image'),
        ),
    ]
