# Generated by Django 5.0.6 on 2025-01-30 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicqualification',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Qualification Name'),
        ),
        migrations.AlterField(
            model_name='coursename',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstName',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastName',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='secondName',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Second Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thirdName',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Third Name'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('P65%', 'بالعمل'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='national_governorate_id',
            field=models.IntegerField(unique=True, verbose_name='الرقم التسلسلي للمحافظة'),
        ),
    ]
