# Generated by Django 5.0.6 on 2025-02-01 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_alter_academicqualification_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='endDate',
        ),
        migrations.RemoveField(
            model_name='course',
            name='startDate',
        ),
    ]
