# Generated by Django 5.0.6 on 2025-02-02 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_remove_course_enddate_remove_course_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='CertDate',
            field=models.DateField(blank=True, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('P', 'بالعمل'), ('S', 'مرضي'), ('C', 'عارضة'), ('A', 'دوري'), ('M', 'غياب'), ('O', 'راحة'), ('F', 'دورة تدريبية'), ('MS', 'مأمورية'), ('P65%', 'بالعمل'), ('l', 'اجازة بدون مرتب')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('Mission', 'مأمورية'), ('P65%', 'بالعمل'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
    ]
