# Generated by Django 5.0.6 on 2025-02-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_course_certdate_alter_employeeattendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='CertDate',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الحصول علي الشهادة'),
        ),
    ]
