# Generated by Django 5.0.6 on 2025-02-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_course_certdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('P', 'بالعمل'), ('S', 'مرضي'), ('C', 'عارضة'), ('A', 'دوري'), ('M', 'غياب'), ('O', 'راحة'), ('F', 'دورة تدريبية'), ('MS', 'مأمورية'), ('P65%', 'بالعمل نصف يوم'), ('l', 'اجازة بدون مرتب')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('Mission', 'مأمورية'), ('P65%', 'بالعمل نصف يوم'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
    ]
