# Generated by Django 5.0.6 on 2025-02-04 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_alter_employeeattendance_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentsAndSections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Department/Section Name')),
            ],
            options={
                'verbose_name': 'Department and Section',
                'verbose_name_plural': 'Departments and Sections',
            },
        ),
        migrations.AddField(
            model_name='employeevacation',
            name='place_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Mission Place (Outside)'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('P', 'بالعمل'), ('S', 'مرضي'), ('C', 'عارضة'), ('A', 'دوري'), ('M', 'غياب'), ('O', 'راحة'), ('F', 'دورة تدريبية'), ('MS', 'مأمورية'), ('P65%', 'بالعمل خمسة وستون'), ('l', 'اجازة بدون مرتب')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('Inside Mission', 'مأمورية داخلية'), ('Outside Mission', 'مأمورية خارجية'), ('P65%', 'بالعمل خمسة وستون'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='employeevacation',
            name='place_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='Department/Section'),
        ),
    ]
