# Generated by Django 5.0.6 on 2025-02-04 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_departmentsandsections_employeevacation_place_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='place_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='الإدارة - القسم'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='place_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='مكان المأمورية الخارجية'),
        ),
    ]
