# Generated by Django 5.0.6 on 2025-02-06 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_employeevacation_place_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentsandsections',
            options={'verbose_name': 'الإدارات والأقسام', 'verbose_name_plural': 'الإدارات والأقسام'},
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='place_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='الإدارة - القسم'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='place_text',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='مكان المأمورية الخارجية'),
        ),
        migrations.AlterField(
            model_name='departmentsandsections',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='الإدارة / القسم'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='status',
            field=models.CharField(choices=[('P', 'بالعمل'), ('S', 'مرضي'), ('C', 'عارضة'), ('A', 'دوري'), ('M', 'غياب'), ('O', 'راحة'), ('F', 'دورة تدريبية'), ('IMS', 'مأمورية داخلية'), ('OMS', 'مأمورية خارجية'), ('P65%', 'بالعمل خمسة وستون'), ('l', 'اجازة بدون مرتب')], max_length=200, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='place_text',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='مكان المأمورية الخارجية'),
        ),
    ]
