# Generated by Django 5.0.6 on 2025-02-06 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_alter_departmentsandsections_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currentEmployer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='Employer Name'),
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Employment Start Date')),
                ('end_date', models.DateField(verbose_name='Employment End Date')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='base.employee')),
                ('employer_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='Employer Name')),
            ],
            options={
                'verbose_name': 'Employment History',
                'verbose_name_plural': 'Employment History',
            },
        ),
    ]
