# Generated by Django 5.0.6 on 2025-02-06 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_alter_employee_currentemployer_employmenthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='previousEmployer',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='previousEmploymentEndDate',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='previousEmploymentStartDate',
        ),
    ]
