# Generated by Django 5.0.6 on 2025-02-06 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_remove_employee_previousemployer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'جهات العمل السابقة', 'verbose_name_plural': 'جهات العمل السابقة'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='currentEmployer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='جهة العمل الحالية'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='جهة العمل الحالية'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(verbose_name='تاريخ نهاية العمل'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ بداية العمل'),
        ),
    ]
