# Generated by Django 5.0.6 on 2025-02-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_alter_employmenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(null=True, verbose_name='تاريخ نهاية العمل'),
        ),
    ]
