# Generated by Django 5.0.6 on 2025-02-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_alter_employmenthistory_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmenthistory',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية العمل'),
        ),
    ]
