# Generated by Django 5.0.6 on 2025-02-09 15:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_alter_employmenthistory_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsandsections',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط ويسمح بالمسافات والرموز "/" و "-"', regex='^[\\u0600-\\u06FF\\s/-]+$')], verbose_name='الإدارة / القسم'),
        ),
    ]
