# Generated by Django 5.0.6 on 2025-02-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_departmentsandsections_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='firstName',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
