# Generated by Django 5.0.6 on 2025-02-09 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_customuser_firstname_customuser_gender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='national_id',
            new_name='nationalId',
        ),
    ]
