# Generated by Django 5.0.6 on 2025-02-09 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_rename_national_id_customuser_nationalid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nationalId',
        ),
    ]
