# Generated by Django 5.0.6 on 2025-02-10 08:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_customuser_firstname_remove_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'بيانات الموظفين', 'verbose_name_plural': 'بيانات الموظفين'},
        ),
        migrations.RemoveField(
            model_name='penalty',
            name='name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='employer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='جهة العمل السابقة'),
        ),
    ]
