# Generated by Django 5.0.6 on 2025-02-18 14:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_alter_employmenthistory_options_remove_penalty_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsandsections',
            name='DepartmentsAndSections_id',
            field=models.IntegerField(default=1, unique=True, verbose_name='الرقم التسلسلي للمحافظة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='secretreport',
            name='description',
            field=models.TextField(validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sections', to='base.departmentsandsections')),
            ],
            options={
                'verbose_name': 'Sections',
                'verbose_name_plural': 'Sections',
            },
        ),
    ]
