# Generated by Django 5.0.6 on 2025-02-20 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_departmentsandsections_departmentsandsections_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currentEmployerSection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sections', verbose_name='جهة العمل الحالية'),
        ),
    ]
