# Generated by Django 5.0.6 on 2025-02-23 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_remove_employmenthistory_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeattendance',
            name='section_place_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sections', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='employeevacation',
            name='section_place_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sections', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='currentEmployerSection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.sections', verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='place_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.departmentsandsections', verbose_name='الإدارة'),
        ),
    ]
