# Generated by Django 5.0.6 on 2025-02-23 14:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_employeeattendance_section_place_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='section_place_link',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='place_link', chained_model_field='department', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sections', verbose_name='القسم'),
        ),
    ]
