# Generated by Django 5.0.6 on 2025-02-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_alter_employeevacation_section_place_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sections',
            old_name='governorate',
            new_name='department',
        ),
    ]
