# Generated by Django 5.0.6 on 2025-03-10 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_rename_governorate_sections_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsandsections',
            name='DepartmentsAndSections_id',
            field=models.IntegerField(unique=True, verbose_name='الرقم التسلسلي'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='base.departmentsandsections'),
        ),
    ]
