# Generated by Django 5.0.6 on 2025-03-10 08:00

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_alter_departmentsandsections_departmentsandsections_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='currentEmployerSection',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='currentEmployer', chained_model_field='department', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sections', verbose_name='القسم'),
        ),
    ]
