# Generated by Django 5.0.6 on 2025-03-18 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_alter_employee_currentemployersection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'جهات العمل السابقة', 'verbose_name_plural': 'جهات العمل السابقة'},
        ),
    ]
