# Generated by Django 5.0.6 on 2025-03-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_alter_employmenthistory_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'dayDate'), name='unique_employee_attendance'),
        ),
    ]
