# Generated by Django 5.0.6 on 2025-04-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_employeeattendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'بيانات الموظفين', 'verbose_name_plural': 'بيانات الموظفين'},
        ),
        migrations.RemoveConstraint(
            model_name='employeeattendance',
            name='unique_employee_attendance',
        ),
        migrations.AlterField(
            model_name='employee',
            name='currentRank',
            field=models.CharField(blank=True, choices=[('First Grade A', 'الدرجة الأولى ا'), ('First Grade B', 'الدرجة الأولى ب'), ('Second Grade A', 'الدرجة الثانية ا'), ('Second Grade B', 'الدرجة الثانية ب'), ('Third Grade A', 'الدرجة الثالثة ا'), ('Third Grade B', 'الدرجة الثالثة ب'), ('Fourth Grade A', 'الدرجة الرابعة ا'), ('Fourth Grade B', 'الدرجة الرابعة ب')], max_length=200, null=True, verbose_name='Current Rank'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeattendance',
            unique_together={('employee', 'dayDate')},
        ),
    ]
