# Generated by Django 5.0.6 on 2025-05-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_alter_employmenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'جهات العمل السابقة', 'verbose_name_plural': 'جهات العمل السابقة'},
        ),
        migrations.RemoveField(
            model_name='employeevacation',
            name='place_link',
        ),
        migrations.RemoveField(
            model_name='employeevacation',
            name='place_text',
        ),
        migrations.RemoveField(
            model_name='employeevacation',
            name='section_place_link',
        ),
    ]
