# Generated by Django 5.0.6 on 2025-05-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_alter_employmenthistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeevacation',
            name='fromDate',
            field=models.DateField(blank=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='toDate',
            field=models.DateField(blank=True, verbose_name='To Date'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='type',
            field=models.CharField(choices=[('Periodic', 'دورية'), ('Casual', 'عارضة'), ('Sick', 'مرضى'), ('Rest', 'راحة'), ('Course', 'دورة تدريبية'), ('Leave Without Pay', 'اجازة بدون مرتب')], max_length=200, verbose_name='Type'),
        ),
    ]
