# Generated by Django 5.0.6 on 2025-05-21 08:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_alter_employeevacation_fromdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, validators=[django.core.validators.RegexValidator(message='الإدخال باللغة العربية فقط', regex='^[\\u0600-\\u06FF\\s]+$')], verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='fromDate',
            field=models.DateField(blank=True, null=True, verbose_name='From Date'),
        ),
        migrations.AlterField(
            model_name='employeevacation',
            name='toDate',
            field=models.DateField(blank=True, null=True, verbose_name='To Date'),
        ),
    ]
