# Generated by Django 5.0.6 on 2025-07-21 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this employee is active. Unselect this to disable attendance and vacation.', verbose_name='active'),
        ),
    ]
