# Generated by Django 5.0.6 on 2025-08-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_employee_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='حدد ما إذا كان هذا المستخدم نشط أم لا. قم بإلغاء التحديد بدلاً من حذف الحسابات.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='حدد ما إذا كان هذا الموظف نشط أم لا. قم بإلغاء التحديد بدلاً من حذف الحسابات.', verbose_name='active'),
        ),
    ]
